on:
  push:
    branches:
      - main
name: Deploy to MAIN branch on push
jobs:
  web-deploy:
    name: Deploy to MAIN
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 173.254.88.148
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}